# Generated by Django 2.2.10 on 2021-09-07 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='variant',
            name='text',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
