# Generated by Django 2.2.10 on 2021-09-07 13:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0002_auto_20210907_1348'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='survey',
            field=models.ForeignKey(default=100, on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='survey.Survey'),
            preserve_default=False,
        ),
    ]
