# Generated by Django 2.2.10 on 2021-09-07 14:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0003_answer_survey'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='choice',
            name='variant',
        ),
        migrations.AddField(
            model_name='choice',
            name='variant',
            field=models.ForeignKey(default=101, on_delete=django.db.models.deletion.CASCADE, to='survey.Variant'),
            preserve_default=False,
        ),
    ]
