# Generated by Django 2.2.10 on 2021-09-07 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0005_auto_20210907_1415'),
    ]

    operations = [
        migrations.AlterField(
            model_name='choice',
            name='variant',
            field=models.ManyToManyField(blank=True, to='survey.Variant'),
        ),
    ]
