# Generated by Django 2.2.10 on 2021-09-07 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0006_auto_20210907_1418'),
    ]

    operations = [
        migrations.AlterField(
            model_name='choice',
            name='variant',
            field=models.ManyToManyField(blank=True, related_name='choices', to='survey.Variant'),
        ),
    ]
